#ifndef GRAPHWINDOW_GLOBAL_H
#define GRAPHWINDOW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHWINDOW_LIBRARY)
#  define GRAPHWINDOWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHWINDOWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHWINDOW_GLOBAL_H
